version: '3.8'

networks:
    laravel:
        name: laravel

services:
    nginx:
        image: nginx:1.21.6-alpine
        container_name: nginx
        working_dir: /var/www/html
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - postgres
            - redis
        ports:
            - "8089:80"
            - '443:443'
        networks:
            - laravel

    php:
        build:
            args:
                user: ${APP_NAME}
                uid: 1000
            context: .
            dockerfile: docker/php.dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"

    postgres:
        image: postgres:13.3
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: "main"
            POSTGRES_USER: "main"
            POSTGRES_PASSWORD: "@uB18D0"
        volumes:
            - "./docker/postgres:/var/lib/postgresql/data"
        expose:
            - 5432
        ports:
            - "6432:5432"
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "7379:6379"
        networks:
            - laravel



